repository:
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        require_code_owner_reviews: false
      restrictions:
        teams:
          - example-team-name

