repository:
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  has_issues: true
protected_branches:
  main:
    required_status_checks:
      strict: false
      contexts:
        - concourse-ci/build-rhel-7-debug
    required_pull_request_reviews:
      dismiss_stale_reviews: false
      require_code_owner_reviews: false
      required_approving_review_count: 0
    required_signatures: false
