repository:
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        #dismiss_stale_reviews - does not work, breaks the protection settings
        #dismiss_stale_reviews: false
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: @woiten-moduscreate
          teams: []
      required_status_checks: null
      restrictions: null
      enforce_admins: false
