name: Create Pull Request
on:
  push:
    branches:
      - dev
    paths:
      - '.github/settings.yml'
      
permissions:
  contents: write
  pull-requests: write
  
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Ensure SHA Pinned Actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0b552a197e44b819629237e065d781f5ca691460
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@d93504a6ff913242c1c512d97ad1f8b302000af5
      with:
        application_id: ${{ secrets.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@dcd5fd746d53dd8de555c0f10bca6c35628be47a
      with:
        token: ${{steps.get_workflow_token.outputs.token}}
        commit-message: Updating
        base: main
        branch: ${{ github.ref }}
        delete-branch: "false"
        title: 'Updated settings.yml'
        body:
          This is a PR creation
