name: Create Pull Request

on:
  push:
    branches:
      - qa
    #paths:
    #  - '.github/settings.yml'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{secrets.API_TOKEN_GITHUB}}
        commit-message: Updating
        #base is the target destination
        base: main
        branch: ${{ github.ref }}
        delete-branch: false
        title: 'Updated settings.yml'
        body:
          This is a PR creation
