name: Create Pull Request

on:
  push:
    branches:
      - dev
    paths:
      - '.github/settings.yml'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{secrets.API_TOKEN_GITHUB}}
        commit-message: Updating
        base: dev
        branch: main
        delete-branch: false
        title: 'Updated settings.yml'
        body: updated settings yml
        assignees: woiten-moduscreate
        reviewers: woiten-moduscreate
        draft: false
