name: Create Pull Request
on:
  push:
    branches:
      - dev
    paths:
      - '.github/settings.yml'
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v1
      with:
        application_id: ${{ secrets.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{steps.get_workflow_token.outputs.token}}
        commit-message: Updating
        base: main
        branch: ${{ github.ref }}
        delete-branch: "false"
        title: 'Updated settings.yml'
        body:
          This is a PR creation
