name: Testing Permissions
on:
  push:
    paths:
      - 'test.txt'
jobs:
  Testing-Permissions:
    runs-on: ubuntu-latest
    permissions:
      contents:read
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@d93504a6ff913242c1c512d97ad1f8b302000af5
      with:
        application_id: ${{ secrets.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

    - name: "Create a new milestone"
      id: create-milestone
      uses: oinume/create-scheduled-milestone-action@v1.0.0
      with:
        title: "1.0.0"
        state: "open"
        description: "v1.0.0"
      env:
        GITHUB_TOKEN: "${{ steps.get_workflow_token.outputs.token }}"

    - name: "Output milestone number"
      run: echo ${{ steps.create-milestone.outputs.number }}
